name: my first workflow              # workflow 이름
on: push                             # event trigger on push

jobs:
  build:                             # job id
    name: Hello world action         # job 이름
    runs-on: ubuntu-latest           # 가상 환경
    steps:
      - name: checkout source code     # step 01 이름
        uses: actions/checkout@master  # 소스코드 checkout

      - name: Build the Docker image
        run: docker build . -f Dockerfile-api -t docker.pkg.github.com/uuidcode/build-docker-test/api:v0.0.4

      - name: login
        run: docker login docker.pkg.github.com -u uuidcode -p d9f93df23e447f76092b98fefa7927f3fc4bf658

      - name: push
        run: docker push docker.pkg.github.com/uuidcode/build-docker-test/api:v0.0.4
